/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.common.base.Preconditions;

public class App {

    public double add(double a, double b) {
        return a + b;
    }

    public double subtract(double a, double b) {
        return a - b;
    }

    public double multiply(double a, double b) {
        return a * b;
    }

    public double divide(double a, double b) {
        Preconditions.checkArgument(b != 0, "Cannot divide by zero");
        return a / b;
    }

    public String getGreeting() {
        return "Simple Calculator App";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        System.out.println("5 + 3 = " + app.add(5, 3));
        System.out.println("5 - 3 = " + app.subtract(5, 3));
        System.out.println("5 * 3 = " + app.multiply(5, 3));
        System.out.println("5 / 3 = " + app.divide(5, 3));
    }
}