/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void add_twoNumbers() {
        App app = new App();
        assertEquals(8.0, app.add(5, 3), 0.01);
    }

    @Test
    void divide_twoNumbers() {
        App app = new App();
        assertEquals(2.5, app.divide(5, 2), 0.01);
    }

    @Test
    void divide_throwsOnZero() {
        App app = new App();
        assertThrows(IllegalArgumentException.class, () -> app.divide(5, 0));
    }
}